syntax = "proto3";

package thorium;

enum EventType {
	EVENT_UNKNOWN = 0;
	EVENT_AUTH_REQUEST = 1;
	EVENT_TEXT_MESSAGE = 2;
	EVENT_FILE_TRANSFER = 3;
	EVENT_READ_RECEIPT = 4;
}

message QuicEnvelope {
	string message_id = 1;
	EventType type = 2;
	uint64 timestamp = 3;
	string sender_id = 4;
	string destination_id = 5;

	bytes encrypted_payload = 6;
}

message ServerAck {
	string message_id = 1;
	bool succes = 2;
	string error_info = 3;
}

message ClientListRequest {}

message ClientListResponse {
    repeated string client_ids = 1;
}

message Packet {
    oneof payload {
        QuicEnvelope envelope = 1;
        ServerAck ack = 2;
        ClientListRequest list_request = 3;
        ClientListResponse list_response = 4;
    }
}
